name: Update package version
description: Updates the version number in a package.json file to match a specified value.
author: The Antitwink™️

branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:  
    description: The version number to set in the package.json file.
    required: true
  package-json-path:  
    description: The path to the package.json file to update.
    required: false
    default: './package.json'
runs:
  using: 'node20'
  main: 'dist/index.js'
  